[tool.poetry]
name = "ConvAssist"
version = "0.1.0"
description = ""
authors = ["Intel Corporation"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
torch = "^2.4.1"
pyspellchecker = "^0.8.1"
websockets = "^13.0.1"
pytest = { version = "8.3.2", optional = true }
pytest-timeout = {version = "^2.3.1",  optional = true }
pytest-cov = {version = "^5.0.0",  optional = true }
nltk = "^3.9.1"
hnswlib = "^0.8.0"
sentence-transformers = "^3.1.1"
pydebugstring = "^1.0.0.2"
spacy = "^3.7.6"

[tool.poetry.extras]
dev = ["pytest", "pytest-timeout", "pytest-cov"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
