# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_run:
  push:
    branches: [ "main", "covassist_cleanup" ]
  pull_request:
    branches: [ "main", "covassist_cleanup" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Poetry setup
      # You may pin to the exact commit or the version.
      uses: ClementWalter/poetry-action@845abd0cfcc6671c045a2f9df189360bb73e64c4
      with:
        os: "ubuntu-latest"
        python-version: "3.12"
        
    - name: Test with pytest
      run: |
        pytest
