# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests

on:
  push:
    branches: [ "main", "covassist_cleanup" ]
  pull_request:
    branches: [ "main", "covassist_cleanup" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unittest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5.2.0
      with:
        python-version: "3.12"

    - name: Cache Python virtual environment
      uses: actions/cache@v4.0.2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-python-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-python-
          
    - name: Install Poetry
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install poetry
        
    - name: Install dependencies
      run: |
        poetry install -E test

    - name: Run tests
      run: |
        source $(poetry env info --path)/bin/activate
        pytest
      working-directory: ./convassist
